In [2]:
import pandas as pd
import polars as pl
from tqdm import tqdm
import re
import ast

# 1. Individual Data Cleaning

## New Car Specs

In [ ]:
# ARUN
car_models = pd.read_csv('../data/MergeData_Test/car_specs_kaggle.csv')
car_models = car_models.dropna(thresh=52252, axis=1)
# car_models = car_models.dropna().reset_index(drop=True)
car_models = car_models.rename(columns = {'Make': 'Brand', 'Modle': 'Model'})
# car_models_dodge = car_models.loc[car_models.Brand == 'Dodge']
car_models#car_models_dodge.shape

In [ ]:
car_models.info()
# set(car_models.Series.unique())

In [ ]:
car_models = car_models[['Brand', 'Model', 'Year_to',
       'Body_type', 'number_of_seats', 'length_mm',
       'width_mm', 'height_mm', 'wheelbase_mm', 'front_track_mm',
       'rear_track_mm', 'curb_weight_kg', 'max_trunk_capacity_l',
       'minimum_trunk_capacity_l', 'maximum_torque_n_m', 'injection_type',
       'cylinder_layout', 'number_of_cylinders', 'engine_type',
       'valves_per_cylinder', 'cylinder_bore_mm', 'stroke_cycle_mm',
       'turnover_of_maximum_torque_rpm', 'capacity_cm3', 'engine_hp',
       'engine_hp_rpm', 'drive_wheels', 'number_of_gears', 'turning_circle_m',
       'transmission', 'mixed_fuel_consumption_per_100_km_l',
       'fuel_tank_capacity_l', 'acceleration_0_100_km/h_s',
       'max_speed_km_per_h', 'fuel_grade', 'back_suspension', 'rear_brakes',
       'front_brakes', 'front_suspension']]

## Car Specifications

In [ ]:
# JEFF
car_models = pd.read_csv('../data/Car_Models.csv')
car_models = car_models.rename(columns = {'Company': 'Brand'})
car_models_dodge = car_models.loc[car_models.Brand == 'Dodge']
car_models_dodge#car_models_dodge.shape

In [ ]:
car_models_dodge['Brand'] = car_models_dodge['Brand'].apply(lambda x: x.lower())
# car_models['model_year'] = car_models['Model'].apply(lambda x: x.lower())
car_models_dodge['Model'] = car_models_dodge['Model'].apply(lambda x: x.lower())

In [ ]:
car_models_dodge.to_csv('../data/MergeData_Test/vehicle_specs_dodge.csv', index = False)

## Reviews

#### Dodge

In [ ]:
# VIKAS
reviews_dodge = pd.read_csv('../data/MergeData_Test/dodge_reviews_vikas.csv', index_col = 'Unnamed: 0')
reviews_dodge.head()

In [ ]:
list(reviews_dodge.Vehicle_Title.unique())

In [ ]:
import re
def clean_brand(review):
    cleaned_review = review.strip()
    cleaned_review = re.sub(r'\r', '', cleaned_review)
    return cleaned_review

reviews_dodge['model_year'] = reviews_dodge['Vehicle_Title'].apply(lambda x: x.split()[0] if x.split()[0].isdigit() else None)
reviews_dodge['model'] = reviews_dodge['Vehicle_Title'].apply(lambda x: x.split()[2])

reviews_dodge.model.unique()

In [ ]:
reviews_dodge['Brand'] = reviews_dodge['Brand'].apply(lambda x: x.lower())
reviews_dodge['model_year'] = reviews_dodge['model_year'].apply(lambda x: x.lower())
reviews_dodge['model'] = reviews_dodge['model'].apply(lambda x: x.lower())

In [ ]:
reviews_dodge.to_csv('../data/MergeData_Test/vehicle_reviews_dodge.csv', index = False)

#### Cleaning all reviews

In [12]:
def clean_brand(review):
    cleaned_review = review.strip()
    cleaned_review = re.sub(r'\r', '', cleaned_review)
    return cleaned_review

unique_brands = ['audi', 'bmw', 'buick', 'cadillac', 'chevrolet', 'chrysler',
        'dodge', 'ford', 'honda', 'hyundai', 'jaguar', 'jeep', 'kia',
        'lexus', 'mazda', 'mercedes‑benz', 'nissan', 'porsche', 'ram',
        'subaru', 'volvo', 'toyota', 'volkswagen']#, 'land-rover']

for brand in tqdm(unique_brands):
    print(brand, len(brand))
    vehicle_reviews = pd.read_csv(f'../data/Reviews/reviews_{str(brand)}.csv', lineterminator='\n', index_col='Unnamed: 0')
    vehicle_reviews['model_year'] = vehicle_reviews['Vehicle_Title'].apply(lambda x: x.split()[0] if x.split()[0].isdigit() else None)
    vehicle_reviews['model'] = vehicle_reviews['Vehicle_Title'].apply(lambda x: x.split()[2])
    vehicle_reviews['Brand'] = vehicle_reviews['Brand'].apply(lambda x: x.lower())
    vehicle_reviews['model_year'] = vehicle_reviews['model_year'].apply(lambda x: x.lower())
    vehicle_reviews['model'] = vehicle_reviews['model'].apply(lambda x: x.lower())
    vehicle_reviews['Review'] = vehicle_reviews['Review'].apply(lambda x: clean_brand(x))
    vehicle_reviews.to_csv(f'../data/Reviews/cleaned_reviews/reviews_{str(brand)}.csv', index=False)
    vehicle_reviews[['Brand', 'model']].drop_duplicates().to_csv(f'../data/Reviews/unique_reviews_by_brand/unique_reviews_{str(brand)}.csv', index=False)
vehicle_reviews

  0%|          | 0/23 [00:00<?, ?it/s]

audi 4

  4%|▍         | 1/23 [00:00<00:04,  4.93it/s]

bmw 3

 13%|█▎        | 3/23 [00:00<00:03,  5.27it/s]

buick 5
cadillac 8

 17%|█▋        | 4/23 [00:00<00:03,  6.04it/s]

chevrolet 9

 26%|██▌       | 6/23 [00:01<00:04,  3.54it/s]

chrysler 8
dodge 5

 30%|███       | 7/23 [00:01<00:04,  3.58it/s]

ford 4

 35%|███▍      | 8/23 [00:02<00:06,  2.46it/s]

honda 5

 39%|███▉      | 9/23 [00:02<00:05,  2.38it/s]

hyundai 7

 43%|████▎     | 10/23 [00:03<00:04,  2.62it/s]

jaguar 6
jeep 4

 52%|█████▏    | 12/23 [00:03<00:02,  3.79it/s]

kia 3

 61%|██████    | 14/23 [00:03<00:02,  4.28it/s]

lexus 5
mazda 5

 65%|██████▌   | 15/23 [00:04<00:01,  4.08it/s]

mercedes‑benz 13

 70%|██████▉   | 16/23 [00:04<00:01,  4.02it/s]

nissan 6

 83%|████████▎ | 19/23 [00:04<00:00,  5.48it/s]

porsche 7
ram 3
subaru 6

 91%|█████████▏| 21/23 [00:05<00:00,  5.25it/s]

volvo 5
toyota 6

 96%|█████████▌| 22/23 [00:05<00:00,  3.24it/s]

volkswagen 10

100%|██████████| 23/23 [00:06<00:00,  3.65it/s]

,Review_Date,Author_Name,Vehicle_Title,Review_Title,Review,Rating,cleaned_review,Brand,model_year,model
0,on 09/18/11 00:19 AM (PDT),wizbang_fl,2007 Volkswagen New Beetle Convertible 2.5 2dr...,"New Beetle- Holds up well & Fun to Drive, but ...",I've had my Beetle Convertible for over 4.5 ye...,4.500,I've had my Beetle Convertible for over 4.5 ye...,volkswagen,2007,new
1,on 07/07/10 05:28 AM (PDT),carlo frazzano,2007 Volkswagen New Beetle Convertible 2.5 PZE...,Quality Review,We bought the car new in 2007 and are generall...,4.375,We bought the car new in 2007 and are generall...,volkswagen,2007,new
2,on 10/19/09 21:41 PM (PDT),NewBeetleDriver,2007 Volkswagen New Beetle Convertible Triple ...,Adore it,"I adore my New Beetle. Even though I'm a male,...",4.375,"I adore my New Beetle. Even though I'm a male,...",volkswagen,2007,new
3,on 01/01/09 19:13 PM (PST),Kayemtee,2007 Volkswagen New Beetle Convertible 2.5 2dr...,Nice Ragtop,My wife chose this car to replace a Sebring co...,4.375,My wife chose this car to replace a Sebring co...,volkswagen,2007,new
4,on 08/02/08 13:43 PM (PDT),jik,2007 Volkswagen New Beetle Convertible 2.5 2dr...,"Luv, luv, luv my dream car",4 of us carpool 1 way 30 min. Backseat ok for...,4.750,4 of us carpool 1 way 30 min. Backseat ok for...,volkswagen,2007,new
...,...,...,...,...,...,...,...,...,...,...
9381,on 02/06/16 03:49 AM (PST),Bill Haberlin,2016 Volkswagen Tiguan SUV S 4dr SUV (2.0L 4cy...,Good Value,I have owned the Tiguan for a year and 4 month...,4.000,I have owned the Tiguan for a year and 4 month...,volkswagen,2016,tiguan
9382,on 02/04/16 05:42 AM (PST),BN,2016 Volkswagen Tiguan SUV S 4dr SUV (2.0L 4cy...,Great Ride - But Typical VW,"Now had 2+ months with SUV. Nice SUV, handles...",3.000,"Now had 2+ months with SUV. Nice SUV, handles...",volkswagen,2016,tiguan
9383,on 01/05/16 00:40 AM (PST),Jason,2016 Volkswagen Tiguan SUV SE 4dr SUV (2.0L 4c...,Quality Over Quantity,Smaller dimensions and my driving experience p...,5.000,Smaller dimensions and my driving experience p...,volkswagen,2016,tiguan
9384,on 11/11/15 19:49 PM (PST),Bill,2016 Volkswagen Tiguan SUV S 4dr SUV (2.0L 4cy...,"Not too big, not too small",We have had our 2016 Tiguan for a month. Prior...,4.000,We have had our 2016 Tiguan for a month. Prior...,volkswagen,2016,tiguan
9385,on 10/22/15 17:04 PM (PDT),Paul,2016 Volkswagen Tiguan SUV S 4dr SUV (2.0L 4cy...,Good pick for its class,The Tiguan S can be had for a reasonable 24k a...,4.000,The Tiguan S can be had for a reasonable 24k a...,volkswagen,2016,tiguan

## NHTSA Safety

In [ ]:
# ARUN
nhtsa_df = pd.read_csv('../data/NHTSA.csv')
nhtsa_df = nhtsa_df.rename(columns={'Make': 'Brand'})
# nhtsa_df_dodge = nhtsa_df.loc[nhtsa_df.Brand == 'DODGE']
# nhtsa_df_dodge

In [ ]:
nhtsa_df_dodge.Brand.unique()

In [ ]:
nhtsa_df_dodge['Brand'] = nhtsa_df_dodge['Brand'].apply(lambda x: x.lower())
nhtsa_df_dodge['Model'] = nhtsa_df_dodge['Model'].apply(lambda x: x.lower())
nhtsa_df_dodge['ModelYear'] = nhtsa_df_dodge['ModelYear'].apply(lambda x: int(x))
nhtsa_df_dodge = nhtsa_df_dodge.reset_index(drop=True)
nhtsa_df_dodge

In [ ]:
nhtsa_df_dodge.to_csv('../data/MergeData_Test/vehicle_safety_dodge.csv', index = False)

## New MSRP

In [ ]:
# ARUN
test_msrp = pd.read_csv('../data/MergeData_Test/test_MSRP.csv')
train_msrp = pd.read_csv('../data/MergeData_Test/train_MSRP.csv')
msrp = pd.concat([test_msrp, train_msrp])
msrp = msrp.rename(columns={'Manufacturer': 'Brand', 'Prod. year':'Year'})
msrp = msrp.sort_values(['Brand', 'Model', 'Year'])
msrp['Brand'] = msrp['Brand'].apply(lambda x: x.lower())
msrp['Model'] = msrp['Model'].apply(lambda x: x.lower())
msrp = msrp[msrp['Price'].notna()]
msrp = msrp[['Brand', 'Model', 'Year', 'Category', 'Leather interior',
       'Fuel type', 'Engine volume', 'Mileage', 'Cylinders', 'Gear box type',
       'Drive wheels', 'Doors', 'Wheel', 'Color', 'Airbags', 'Price']]
msrp = msrp.loc[msrp.Brand.isin(unique_brands)].reset_index(drop=True)
msrp

## MSRP

In [ ]:
# CASSIDY
msrp = pd.read_excel('../data/Car_MSRP.xlsx')
msrp.head()

In [ ]:
msrp_land_rover.loc[msrp.Brand == 'land']['Brand']

In [ ]:
def extract_info(text):
    pattern = r'(\d{4})\s(.+?)\s(.+)'
    match = re.match(pattern, text)
    if match:
        year = match.group(1)
        brand = match.group(2)
        model = match.group(3)
        return year, brand, model
    
    return None, None, None

msrp[['Year', 'Brand', 'Model']] = msrp['Make-Model'].apply(extract_info).apply(pd.Series)
msrp['Model'] = msrp.Model.apply(lambda x: re.sub(re.compile(r'\xa0'), ' ', x))
msrp['Brand'] = msrp['Brand'].apply(lambda x: x.lower())
msrp['Model'] = msrp['Model'].apply(lambda x: x.lower())
msrp[['Year', 'Brand', 'Model', 'MSRP Price', 'Starting Market Average']].to_csv('../data/MergeData_Test/Brand_Model_MSRP.csv', index=False)

In [ ]:
# msrp_dodge = msrp.loc[msrp.Brand == 'dodge'].reset_index(drop=True)
msrp.reset_index(drop=True).to_csv('../data/MergeData_Test/vehicle_msrp.csv', index = False)
msrp

In [ ]:
print('Unique Years: ', msrp_dodge.Year.unique())
print('Unique Brands: ', msrp_dodge.Brand.unique())
print('Unique Models: ', msrp_dodge.Model.unique())

In [ ]:
msrp_dodge

# 2. Joining datasets For Dodge Only

## Join MSRP & Reviews

In [ ]:
vehicle_msrp = pd.read_csv('../data/MergeData_Test/vehicle_msrp_dodge.csv')
vehicle_reviews = pd.read_csv('../data/MergeData_Test/vehicle_reviews_dodge.csv')
# vehicle_safety = pd.read_csv('../data/MergeData_Test/vehicle_safety_dodge.csv')
# vehicle_specs = pd.read_csv('../data/MergeData_Test/vehicle_specs_dodge.csv')

In [ ]:
vehicle_msrp = vehicle_msrp.drop(columns = ['Make-Model', 'Description'])
vehicle_msrp.columns

In [ ]:
vehicle_reviews.columns#.loc[vehicle_reviews.model == 'charger']['model_year'].unique()

In [ ]:
vehicle_mean_online_rating = vehicle_reviews.groupby(['Brand', 'model'])['Rating'].mean()

vehicle_msrp_reviews = vehicle_msrp.merge(vehicle_mean_online_rating,
                                        how='inner',
                                        left_on = ['Brand', 'Model'],
                                        right_on = ['Brand', 'model']).reset_index(drop=True)

vehicle_msrp_reviews = vehicle_msrp_reviews.rename(columns = {'MSRP Price' : 'MSRP', 
                                       'Starting Market Average': 'Starting_Market_MSRP',
                                      'Rating': 'Online_Review_Rating',
                                      'Year': 'Model_Year'})
vehicle_msrp_reviews = vehicle_msrp_reviews[['Brand', 'Model', 'Model_Year', \
                                             'MSRP', 'Starting_Market_MSRP', 'Online_Review_Rating']]
vehicle_msrp_reviews

In [ ]:
vehicle_msrp_reviews.to_csv('../data/MergeData_Test/output/vehicle_msrp_reviews.csv', index = False)

## Join MSRP_Reviews & Specs

In [ ]:
vehicle_msrp_reviews = pd.read_csv('../data/MergeData_Test/output/vehicle_msrp_reviews.csv')
vehicle_specs = pd.read_csv('../data/MergeData_Test/vehicle_specs_dodge.csv')

In [ ]:
vehicle_specs = vehicle_specs[['Brand', 'Model', 'Body Type']]

# vehicle_specs = vehicle_specs[['Brand', 'Model', 'Horsepower', 'Torque', 'Transmission Type',
#        'Drivetrain', 'Fuel Economy', 'Number of Doors', 'Price',
#        'Model Year Range', 'Body Type', 'Engine Type', 'Number of Cylinders']]

In [ ]:
vehicle_msrp_reviews_specs = vehicle_msrp_reviews.merge(vehicle_specs,
                                        how='inner',
                                        left_on = ['Brand', 'Model'],
                                        right_on = ['Brand', 'Model']).reset_index(drop=True)

vehicle_msrp_reviews_specs

In [ ]:
vehicle_msrp_reviews_specs.to_csv('../data/MergeData_Test/output/vehicle_msrp_reviews_specs.csv', index = False)

## Join MSRP_Reviews_Specs & Safety

In [ ]:
import ast 
vehicle_msrp_reviews_specs = pd.read_csv('../data/MergeData_Test/output/vehicle_msrp_reviews_specs.csv')

In [ ]:
vehicle_safety = pd.read_csv('../data/MergeData_Test/vehicle_safety_dodge.csv')
vehicle_safety = vehicle_safety.dropna().reset_index(drop=True)
vehicle_safety.SafetyRatings = vehicle_safety.SafetyRatings.apply(lambda x: ast.literal_eval(x)[0])
vehicle_safety['Safety_Rating'] = vehicle_safety.SafetyRatings.apply(lambda x: x['OverallRating']) 
vehicle_safety['Complaints_Count'] = vehicle_safety.SafetyRatings.apply(lambda x: x['ComplaintsCount']) 
vehicle_safety

In [ ]:
vehicle_safety = vehicle_safety.dropna()
vehicle_safety = vehicle_safety.loc[(vehicle_safety.Safety_Rating != 'Not Rated')]
vehicle_safety['Safety_Rating'] = vehicle_safety.Safety_Rating.apply(lambda x: int(x))
vehicle_safety['Complaints_Count'] = vehicle_safety.Complaints_Count.apply(lambda x: int(x))
vehicle_safety_grouped = vehicle_safety.groupby(['Brand', 'Model']).agg(Avg_Safety_Rating=('Safety_Rating', 'mean'), 
                                                                        Avg_Complaints_Count=('Complaints_Count', 'mean')).reset_index()
vehicle_safety_grouped
# vehicle_safety.Safety_Rating.unique()#

In [ ]:
vehicle_msrp_reviews_specs_safety = vehicle_msrp_reviews_specs.merge(vehicle_safety_grouped,
                                        how='inner',
                                        left_on = ['Brand', 'Model'],
                                        right_on = ['Brand', 'Model']).reset_index(drop=True)

vehicle_msrp_reviews_specs_safety

## Unique Brands & Models

In [37]:
msrp = pd.read_csv('../data/MergeData_Test/Brand_Model_MSRP.csv')
msrp_land = msrp.loc[msrp.Brand == 'land'] # to fix error later concat
msrp = msrp.loc[msrp.Brand != 'land'] # error with land rover
msrp_land['Brand'] = 'land-rover'
msrp_land.Model = msrp_land.Model.apply(lambda x: x[6:])
msrp = pd.concat([msrp, msrp_land]).reset_index(drop=True)
msrp

     Year       Brand               Model  MSRP Price  Starting Market Average
0    2024        audi                 sq5       58195                    58045
1    2024        audi           q8 e‑tron       75595                    71650
2    2024        audi                  a3       36495                    34811
3    2024        audi                  s3       48095                    47971
4    2024        audi                rs 3       62795                    62633
..    ...         ...                 ...         ...                      ...
270  2024  land-rover            defender       57875                    58206
271  2023  land-rover  range rover evoque       46175                    45765
272  2024  land-rover   range rover velar       62775                    62501
273  2024  land-rover           discovery       61375                    61726
274  2023  land-rover     discovery sport       44475                    43249

[275 rows x 5 columns]

In [38]:
unique_brands = msrp.Brand.unique()
msrp_brand = msrp.loc[msrp.Brand == 'audi']#'mercedes‑benz']
unique_models = msrp_brand.Model.unique()

unique_brands, unique_models

(array(['audi', 'bmw', 'buick', 'cadillac', 'chevrolet', 'chrysler',
        'dodge', 'ford', 'honda', 'hyundai', 'jaguar', 'jeep', 'kia',
        'lexus', 'mazda', 'mercedes‑benz', 'nissan', 'porsche', 'ram',
        'subaru', 'volvo', 'toyota', 'volkswagen', 'land-rover'],
       dtype=object),
 array(['sq5', 'q8 e‑tron', 'a3', 's3', 'rs 3', 'q4 e‑tron', 'e‑tron s',
        'e‑tron gt', 'rs e‑tron gt', 'rs 6 avant', 'rs 7', 'sq7',
        'a6 allroad', 's6', 'sq8', 'rs q8', 's8', 's7', 'a6', 'q3'],
       dtype=object))

In [6]:
len(unique_brands)

24

# 3. Joining for all brands

## Joining MSRP & Reviews

In [39]:
# vehicle_msrp = pd.read_csv(fr'../data/MergeData_Test/vehicle_msrp.csv')
test_msrp = pd.read_csv('../data/MergeData_Test/test_MSRP.csv')
train_msrp = pd.read_csv('../data/MergeData_Test/train_MSRP.csv')
msrp = pd.concat([test_msrp, train_msrp])
msrp = msrp.rename(columns={'Manufacturer': 'Brand', 'Prod. year':'Year'})
msrp = msrp.sort_values(['Brand', 'Model', 'Year'])
msrp['Brand'] = msrp['Brand'].apply(lambda x: x.lower())
msrp['Model'] = msrp['Model'].apply(lambda x: x.lower())
msrp['Category'] = msrp['Category'].apply(lambda x: x.lower())
msrp['Doors'] = msrp.Doors.apply(lambda x: int(x[:2]) if x[:2].isdigit() else None)
msrp = msrp[msrp['Price'].notna()]
msrp = msrp[['Brand', 'Model', 'Year', 'Category', 'Leather interior',
       'Fuel type', 'Engine volume', 'Mileage', 'Cylinders', 'Gear box type',
       'Drive wheels', 'Doors', 'Wheel', 'Color', 'Airbags', 'Price']]
vehicle_msrp = msrp.loc[msrp.Brand.isin(unique_brands)].reset_index(drop=True)

vehicle_reviews = pd.DataFrame()
for brand in tqdm(unique_brands):
    # print(brand, len(brand))
    temp = pd.read_csv(fr'../data/Reviews/reviews_{str(brand)}_1.csv', lineterminator='\n')
    vehicle_reviews = pd.concat([vehicle_reviews, temp])
    
# lets target certain models that can be easily corrected manually so they can easily be added to the db

#######################################
# audi

#######################################

#######################################
# audi

#######################################
    
vehicle_mean_online_rating = vehicle_reviews.groupby(['Brand', 'model', 'model_year'])['Rating'].mean()

vehicle_msrp_reviews = vehicle_msrp.merge(
    vehicle_mean_online_rating,
    how='inner',
    left_on = ['Brand', 'Model', 'Year'],
    right_on = ['Brand', 'model', 'model_year'], copy=False
).reset_index(drop=True)

# vehicle_msrp_reviews = vehicle_msrp_reviews.rename(columns = {'MSRP Price' : 'MSRP', 
#                                        'Starting Market Average': 'Starting_Market_MSRP',
#                                       'Rating': 'Online_Review_Rating',
#                                       'Year': 'Model_Year'})
# vehicle_msrp_reviews = vehicle_msrp_reviews[['Brand', 'Model', 'MSRP', \
#                                              'Starting_Market_MSRP', 'Online_Review_Rating']]

vehicle_msrp_reviews

100%|██████████| 24/24 [00:02<00:00,  8.99it/s]

,Brand,Model,Year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price,Rating
0,audi,a3,2011,hatchback,Yes,Petrol,2.0 Turbo,145600 km,4.0,Manual,Front,4.0,Left wheel,Black,8,19444.0,3.951923
1,audi,a3,2012,jeep,Yes,Diesel,2,167398 km,4.0,Automatic,Front,4.0,Left wheel,White,12,1568.0,5.000000
2,audi,a3,2012,sedan,Yes,Diesel,2,174966 km,4.0,Automatic,Front,4.0,Left wheel,Black,12,2587.0,5.000000
3,audi,a3,2016,hatchback,Yes,Hybrid,1.4,104805 km,4.0,Automatic,Front,4.0,Left wheel,White,0,6743.0,4.115385
4,audi,a3,2016,sedan,Yes,Petrol,2,70414 km,4.0,Automatic,4x4,4.0,Left wheel,White,12,470.0,4.115385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9255,volvo,v50,2010,goods wagon,No,Diesel,1.6 Turbo,180300 km,4.0,Manual,Front,4.0,Left wheel,Black,8,16308.0,5.000000
9256,volvo,xc90,2003,jeep,Yes,Petrol,2.5 Turbo,363200 km,6.0,Automatic,4x4,4.0,Left wheel,Green,6,9100.0,3.957143
9257,volvo,xc90,2010,jeep,Yes,Petrol,3.2,102000 km,6.0,Tiptronic,Front,4.0,Left wheel,White,10,21012.0,4.423611
9258,volvo,xc90,2010,jeep,Yes,Petrol,3.2,124000 km,6.0,Tiptronic,4x4,4.0,Left wheel,Black,9,24148.0,4.423611
9259,volvo,xc90,2013,jeep,Yes,Petrol,3.2,169138 km,6.0,Automatic,4x4,4.0,Left wheel,White,12,2509.0,4.291667

## MSRP+Reviews & Specs

In [40]:
# JEFF

# car_models = pd.read_csv('../data/Car_Models.csv')
# car_models = car_models.rename(columns = {'Company': 'Brand'})
car_models = pd.read_csv('../data/MergeData_Test/car_specs_kaggle.csv')


car_models = car_models.rename(columns = {'Make': 'Brand', 'Modle': 'Model'})
# car_models = car_models.sort_values(['Brand', 'Model', 'Year_to'])
# car_models = car_models.drop_duplicates(subset = ['Brand', 'Model'], keep='last').reset_index(drop=True)
# car_models = car_models.dropna(thresh=52252, axis=1)
# car_models = car_models.dropna().reset_index(drop=True)

car_models['Brand'] = car_models['Brand'].apply(lambda x: x.lower())
car_models['Model'] = car_models['Model'].apply(lambda x: x.lower())
car_models['Series'] = car_models['Series'].apply(lambda x: x.lower())


car_models = car_models[['Brand', 'Model', 'Year_to','Series']]\
.drop_duplicates(subset = ['Brand', 'Model', 'Year_to', 'Series'], keep='last').reset_index(drop=True)
car_models = car_models[car_models['Year_to'].notna()]
car_models['Year_to'] = car_models.Year_to.astype(int)
car_models = car_models.set_index(['Brand', 'Model','Year_to', 'Series'])
#,'Body_type', 'number_of_seats', 'length_mm',
       # 'width_mm', 'height_mm', 'wheelbase_mm', 'curb_weight_kg',
       # 'maximum_torque_n_m', 'injection_type', 'cylinder_layout',
       # 'number_of_cylinders', 'engine_type', 'valves_per_cylinder',
       # 'turnover_of_maximum_torque_rpm', 'capacity_cm3', 'engine_hp',
       # 'engine_hp_rpm', 'drive_wheels', 'number_of_gears', 'transmission',
       # 'fuel_tank_capacity_l', 'fuel_grade', 'back_suspension', 'rear_brakes',
       # 'front_brakes', 'front_suspension']]
    

vehicle_msrp_reviews_specs = vehicle_msrp_reviews.merge(car_models,
                                        how='inner',
                                        left_on = ['Brand', 'Model', 'Year', 'Category'],
                                        right_on = ['Brand', 'Model','Year_to', 'Series'], copy=False).reset_index(drop=True)

vehicle_msrp_reviews_specs
# car_models

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3269: DtypeWarning:

Columns (9,11,12,13,14,15,16,17,19,20,24,27,29,33,43,44,47,49,51,69,75,77) have mixed types.Specify dtype option on import or set low_memory=False.

,Brand,Model,Year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price,Rating
0,audi,a3,2016,sedan,Yes,Petrol,2,70414 km,4.0,Automatic,4x4,4.0,Left wheel,White,12,470.0,4.115385
1,audi,a4,1999,sedan,Yes,Petrol,1.9,193243 km,4.0,Manual,Front,4.0,Left wheel,Silver,6,6899.0,4.259259
2,audi,a4,2001,sedan,Yes,CNG,2.8,25000 km,6.0,Tiptronic,Front,4.0,Left wheel,Silver,8,5018.0,4.201389
3,audi,a4,2016,sedan,Yes,Diesel,2.0 Turbo,98000 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,0,46258.0,3.583333
4,audi,a5,2011,coupe,Yes,Petrol,2,1000 km,4.0,Tiptronic,4x4,2.0,Left wheel,Black,8,16500.0,4.290000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,99000 km,4.0,Tiptronic,Front,4.0,Left wheel,Silver,9,17249.0,4.291667
1136,volkswagen,passat,2015,sedan,Yes,Petrol,1.8,36235 km,4.0,Automatic,Front,4.0,Left wheel,Black,12,2666.0,4.291667
1137,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,63523 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,8,20385.0,4.291667
1138,volvo,s60,2013,sedan,Yes,Petrol,2.5,306266 km,5.0,Automatic,4x4,4.0,Left wheel,White,12,314.0,4.012500
1139,volvo,s70,2000,sedan,Yes,Petrol,2.4,306786 km,5.0,Automatic,Front,4.0,Left wheel,Silver,12,470.0,4.522321

## MSRP+Reviews+Specs & Safety

In [41]:
nhtsa_df = pd.read_csv('../data/NHTSA.csv')
nhtsa_df = nhtsa_df.rename(columns={'Make': 'Brand'})
nhtsa_df['Brand'] = nhtsa_df['Brand'].apply(lambda x: x.lower())
nhtsa_df['Model'] = nhtsa_df['Model'].apply(lambda x: x.lower())
nhtsa_df['ModelYear'] = nhtsa_df['ModelYear'].apply(lambda x: int(x))
nhtsa_df = nhtsa_df.reset_index(drop=True)
vehicle_safety = nhtsa_df.dropna().reset_index(drop=True)
vehicle_safety.SafetyRatings = vehicle_safety.SafetyRatings.apply(lambda x: ast.literal_eval(x)[0])
vehicle_safety['Safety_Rating'] = vehicle_safety.SafetyRatings.apply(lambda x: x['OverallRating']) 
vehicle_safety['Complaints_Count'] = vehicle_safety.SafetyRatings.apply(lambda x: x['ComplaintsCount']) 
vehicle_safety = vehicle_safety.dropna()
vehicle_safety = vehicle_safety.loc[(vehicle_safety.Safety_Rating != 'Not Rated')]
vehicle_safety['Safety_Rating'] = vehicle_safety.Safety_Rating.apply(lambda x: int(x))
vehicle_safety['Complaints_Count'] = vehicle_safety.Complaints_Count.apply(lambda x: int(x))

# lets target certain models that can be easily corrected manually so they can easily be added to the db

#######################################
# audi
vehicle_safety.Model = vehicle_safety.Model.apply(lambda x: x.replace('audi ', '') if 'audi ' in x else x)
#######################################


vehicle_safety_grouped = vehicle_safety.groupby(['Brand', 'Model', 'ModelYear'])\
                        .agg(Avg_Safety_Rating=('Safety_Rating', 'mean'), 
                             Avg_Complaints_Count=('Complaints_Count', 'mean'))

vehicle_msrp_reviews_specs_safety = vehicle_msrp_reviews_specs.merge(vehicle_safety_grouped,
                                        how='inner',
                                        left_on = ['Brand', 'Model', 'Year'],
                                        right_on = ['Brand', 'Model', 'ModelYear'], copy=False).reset_index(drop=True)

vehicle_msrp_reviews_specs_safety

,Brand,Model,Year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price,Rating,Avg_Safety_Rating,Avg_Complaints_Count
0,audi,a3,2016,sedan,Yes,Petrol,2,70414 km,4.0,Automatic,4x4,4.0,Left wheel,White,12,470.0,4.115385,5.0,87.0
1,audi,a4,2016,sedan,Yes,Diesel,2.0 Turbo,98000 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,0,46258.0,3.583333,5.0,23.0
2,audi,a6,2014,sedan,Yes,Petrol,3,164488 km,6.0,Automatic,4x4,4.0,Left wheel,Silver,12,627.0,4.515625,5.0,34.0
3,audi,a6,2014,sedan,Yes,Petrol,2,279722 km,4.0,Automatic,4x4,4.0,Left wheel,Black,0,18817.0,4.515625,5.0,34.0
4,audi,a6,2014,sedan,Yes,Petrol,2,279722 km,4.0,Automatic,4x4,4.0,Left wheel,Black,0,18817.0,4.515625,5.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,volkswagen,passat,2015,sedan,Yes,Diesel,0.2,88531 km,4.0,Automatic,Front,4.0,Left wheel,Red,12,1333.0,4.291667,5.0,210.0
752,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,99000 km,4.0,Tiptronic,Front,4.0,Left wheel,Silver,9,17249.0,4.291667,5.0,210.0
753,volkswagen,passat,2015,sedan,Yes,Petrol,1.8,36235 km,4.0,Automatic,Front,4.0,Left wheel,Black,12,2666.0,4.291667,5.0,210.0
754,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,63523 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,8,20385.0,4.291667,5.0,210.0
755,volvo,s60,2013,sedan,Yes,Petrol,2.5,306266 km,5.0,Automatic,4x4,4.0,Left wheel,White,12,314.0,4.012500,5.0,74.0

In [42]:
column_mapping = {
    'Brand': 'brand',
    'Model': 'model',
    'Year': 'year',
    'Category': 'category',
    'Leather interior': 'leather_interior',
    'Fuel type': 'fuel_type',
    'Engine volume': 'engine_volume',
    'Mileage': 'mileage',
    'Cylinders': 'cylinders',
    'Gear box type': 'gear_box_type',
    'Drive wheels': 'drive_wheels',
    'Doors': 'doors',
    'Wheel': 'wheel',
    'Color': 'color',
    'Airbags': 'airbags',
    'Price': 'price',
    'Rating': 'rating',
    'Avg_Safety_Rating': 'avg_safety_rating',
    'Avg_Complaints_Count': 'avg_complaints_count'
}

vehicle_msrp_reviews_specs_safety.rename(columns=column_mapping, inplace=True)
vehicle_msrp_reviews_specs_safety

,brand,model,year,category,leather_interior,fuel_type,engine_volume,mileage,cylinders,gear_box_type,drive_wheels,doors,wheel,color,airbags,price,rating,avg_safety_rating,avg_complaints_count
0,audi,a3,2016,sedan,Yes,Petrol,2,70414 km,4.0,Automatic,4x4,4.0,Left wheel,White,12,470.0,4.115385,5.0,87.0
1,audi,a4,2016,sedan,Yes,Diesel,2.0 Turbo,98000 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,0,46258.0,3.583333,5.0,23.0
2,audi,a6,2014,sedan,Yes,Petrol,3,164488 km,6.0,Automatic,4x4,4.0,Left wheel,Silver,12,627.0,4.515625,5.0,34.0
3,audi,a6,2014,sedan,Yes,Petrol,2,279722 km,4.0,Automatic,4x4,4.0,Left wheel,Black,0,18817.0,4.515625,5.0,34.0
4,audi,a6,2014,sedan,Yes,Petrol,2,279722 km,4.0,Automatic,4x4,4.0,Left wheel,Black,0,18817.0,4.515625,5.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,volkswagen,passat,2015,sedan,Yes,Diesel,0.2,88531 km,4.0,Automatic,Front,4.0,Left wheel,Red,12,1333.0,4.291667,5.0,210.0
752,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,99000 km,4.0,Tiptronic,Front,4.0,Left wheel,Silver,9,17249.0,4.291667,5.0,210.0
753,volkswagen,passat,2015,sedan,Yes,Petrol,1.8,36235 km,4.0,Automatic,Front,4.0,Left wheel,Black,12,2666.0,4.291667,5.0,210.0
754,volkswagen,passat,2015,sedan,Yes,Petrol,1.8 Turbo,63523 km,4.0,Tiptronic,Front,4.0,Left wheel,Black,8,20385.0,4.291667,5.0,210.0
755,volvo,s60,2013,sedan,Yes,Petrol,2.5,306266 km,5.0,Automatic,4x4,4.0,Left wheel,White,12,314.0,4.012500,5.0,74.0

In [43]:
vehicle_msrp_reviews_specs_safety.to_csv('../data/output_data/dataset_v1.csv', index = False)

# Descriptive Stats of the final merged dataset

In [10]:
BMYC_count.year.min(), BMYC_count.year.max()

(2011, 2018)

In [3]:
# BMYC_count = vehicle_msrp_reviews_specs_safety.groupby(['brand', 'model', 'year', 'category']).mean().reset_index()
# BMYC_count.to_csv('../data/output_data/BMYC_stats.csv', index = False)

BMYC_count = pd.read_csv('../data/output_data/BMYC_stats.csv')
BMYC_count

,brand,model,year,category,cylinders,doors,airbags,price,rating,avg_safety_rating,avg_complaints_count
0,audi,a3,2016,sedan,4.000000,4.000000,12.000000,470.000000,4.115385,5.0,87.0
1,audi,a4,2016,sedan,4.000000,4.000000,0.000000,46258.000000,3.583333,5.0,23.0
2,audi,a6,2014,sedan,4.400000,4.000000,4.800000,11635.200000,4.515625,5.0,34.0
3,audi,s3,2016,sedan,4.000000,4.000000,12.000000,14113.000000,4.750000,5.0,11.0
4,chevrolet,camaro,2015,cabriolet,4.000000,4.000000,4.000000,48277.000000,4.275862,5.0,182.0
5,chevrolet,cruze,2012,sedan,4.000000,4.000000,6.926829,13036.024390,3.726786,5.0,832.0
6,chevrolet,impala,2013,sedan,6.000000,4.000000,12.000000,470.000000,4.025000,4.0,266.0
7,chevrolet,malibu,2012,sedan,4.000000,4.000000,4.470588,20085.000000,3.277778,4.0,854.0
8,chevrolet,malibu,2013,sedan,4.000000,4.000000,6.823529,14559.882353,4.209375,5.0,847.0
9,chevrolet,malibu,2014,sedan,4.000000,4.000000,4.533333,20411.933333,4.234375,5.0,310.0
10,chevrolet,malibu,2016,sedan,4.000000,4.000000,6.400000,19735.000000,3.640625,5.0,725.0
11,chevrolet,malibu,2018,sedan,4.000000,4.000000,11.000000,18553.500000,4.800000,5.0,497.0
12,chevrolet,sonic,2016,sedan,4.000000,4.000000,10.000000,21000.000000,4.500000,5.0,44.0
13,chevrolet,spark,2015,hatchback,4.000000,4.000000,4.000000,10347.000000,4.101852,4.0,61.0
14,chevrolet,volt,2015,sedan,4.000000,4.000000,8.000000,19287.000000,4.664062,5.0,34.0
15,dodge,avenger,2014,sedan,6.000000,4.000000,12.000000,282.000000,3.333333,4.0,199.0
16,dodge,caliber,2012,hatchback,4.000000,4.000000,8.000000,9408.000000,4.500000,3.0,47.0
17,dodge,challenger,2015,coupe,6.000000,2.000000,12.000000,4861.000000,4.564286,5.0,111.0
18,ford,focus,2015,sedan,3.888889,4.000000,8.111111,12161.111111,2.712963,5.0,800.0
19,ford,mustang,2012,coupe,6.000000,2.000000,8.500000,22736.500000,4.628472,4.0,459.0
20,ford,mustang,2014,coupe,5.333333,2.666667,5.333333,40371.000000,4.515625,4.0,346.0
21,honda,accord,2015,sedan,4.000000,4.000000,12.000000,8781.000000,4.089602,5.0,524.0
22,honda,accord,2016,coupe,4.000000,2.000000,12.000000,9722.000000,4.160000,5.0,408.0
23,honda,accord,2016,sedan,4.000000,4.000000,12.000000,5370.500000,4.160000,5.0,408.0
24,honda,civic,2015,coupe,4.000000,4.000000,4.000000,44849.000000,4.362500,4.5,301.0
25,hyundai,accent,2013,sedan,4.000000,4.000000,8.666667,8023.000000,4.493750,4.0,90.0
26,hyundai,elantra,2016,sedan,4.106195,4.000000,7.185841,18438.681416,4.175439,5.0,208.0
27,hyundai,elantra,2017,coupe,4.000000,4.000000,4.000000,25032.000000,4.380282,4.0,281.5
28,hyundai,elantra,2017,sedan,4.000000,4.000000,8.646154,15166.646154,4.380282,4.0,281.5
29,hyundai,sonata,2012,sedan,4.076190,4.000000,5.219048,6632.933333,3.876147,5.0,1391.0
30,kia,forte,2012,sedan,4.000000,4.000000,10.000000,17876.000000,4.325893,4.0,228.0
31,kia,forte,2016,sedan,4.000000,4.000000,10.000000,16935.000000,4.531250,5.0,98.0
32,kia,optima,2014,sedan,4.117647,4.000000,7.058824,15222.333333,4.302083,5.0,437.0
33,kia,optima,2015,sedan,4.000000,4.000000,6.444444,13630.407407,3.879464,5.0,674.0
34,kia,rio,2017,sedan,4.000000,4.000000,2.000000,17249.000000,4.000000,4.0,15.0
35,nissan,altima,2012,sedan,4.000000,4.000000,12.000000,914.333333,3.813596,4.0,408.0
36,nissan,altima,2015,sedan,4.000000,4.000000,11.200000,8602.900000,3.857143,5.0,812.0
37,nissan,maxima,2014,sedan,6.000000,4.000000,12.000000,3136.000000,4.237500,4.0,85.0
38,nissan,sentra,2017,sedan,4.000000,4.000000,12.000000,1620.333333,3.304348,4.0,168.0
39,nissan,versa,2012,hatchback,4.000000,4.000000,8.000000,7291.333333,3.155303,4.0,474.0
40,nissan,versa,2012,sedan,4.000000,4.000000,4.666667,11499.000000,3.155303,4.0,474.0
41,toyota,avalon,2015,sedan,5.000000,4.000000,12.000000,18555.333333,4.157895,5.0,46.0
42,toyota,avalon,2018,sedan,8.000000,4.000000,10.000000,62095.000000,3.920000,5.0,23.0
43,toyota,camry,2018,sedan,4.157895,4.000000,11.473684,24727.894737,3.639640,5.0,522.0
44,toyota,corolla,2013,sedan,4.000000,4.000000,10.666667,9084.333333,4.122024,4.0,187.0
45,toyota,corolla,2016,sedan,4.000000,4.000000,11.333333,9617.333333,4.128571,5.0,190.0
46,toyota,corolla,2018,sedan,4.000000,4.000000,12.000000,6272.333333,4.000000,5.0,110.0
47,toyota,prius,2011,hatchback,4.087719,3.964912,9.087719,10119.719298,4.327273,5.0,435.0
48,toyota,prius,2015,hatchback,4.114286,4.000000,10.342857,12135.285714,4.519817,4.0,86.0
49,volkswagen,jetta,2014,sedan,4.031250,4.000000,9.156250,7812.437500,4.063725,5.0,356.0
50,volkswagen,passat,2015,sedan,4.000000,4.000000,9.125000,12721.000000,4.291667,5.0,210.0
51,volvo,s60,2013,sedan,5.000000,4.000000,12.000000,314.000000,4.012500,5.0,74.0

In [16]:
# ! pip install pandas plotly ipywidgets

In [17]:
# ! pip install --upgrade altair

In [4]:
import altair as alt

alt.Chart(BMYC_count).mark_circle().encode(
    alt.X('year:O').scale(domainMin=2000, domainMax=2023),
    y='price',
    color='brand',
    size='avg_complaints_count',
    tooltip=['brand', 'model', 'category', 'price', 'rating', 'avg_complaints_count'],
    # x.scale(domain=(2011, 2018)),

).properties(
    width=500,
    height=400
).interactive()

alt.Chart(...)

In [4]:
# ! pip install anywidget
# ! pip install 'ipywidgets~=7.6.5'

## End